# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 71a8d50b771da825e6e12e33854abdfbe29d98bd2cbdf465162ef425fc6b8a49bec33312e19b43c8ec55b70ca4e29b73d480ec9e035825b6c80437b1ea05fd4f

test:
  secret_key_base: 0b02f955eebcbafe55bb90b1c4b63e1dcf190a7769cfb8c3955a6e2632996c3a37ddd7daff14c6a2aa0152ef60e74b1e28c3502de3eb711b4f6703f1b7dfe05f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
